name: ETL diario

on:
  schedule:
    - cron: "0 6 * * *"   # todos los días a las 6 AM UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar ETL
        env:
          AZURE_SQL_SERVER: incidentes.database.windows.net
          AZURE_SQL_DATABASE: incidentes
          AZURE_SQL_USER: Luzkalid
          AZURE_SQL_PASSWORD: Tacna123
        run: python -m etl.main
